name: Build, Test and Deploy

on:
  push:

env:
  CI_REGISTRY_IMAGE: "${{ secrets.CI_REGISTRY }}/aibot"

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.CI_REGISTRY }}
          username: ${{ secrets.CI_REGISTRY_USER }}
          password: ${{ secrets.CI_REGISTRY_PASSWORD }}

      - name: Docker Build
        uses: docker/build-push-action@v4
        with:
          cache-from: ${{ env.CI_REGISTRY_IMAGE }}:latest
          pull: true
          file: standalone/Dockerfile
          tags: ${{ env.CI_REGISTRY_IMAGE }}:${{ github.sha }}
          push: true
          build-args: |
            COMMIT_HASH=${{ github.sha }}

  tag-latest-docker:
    runs-on: ubuntu-latest
    needs:
      - build-docker
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.CI_REGISTRY }}
          username: ${{ secrets.CI_REGISTRY_USER }}
          password: ${{ secrets.CI_REGISTRY_PASSWORD }}

      - uses: beeper/docker-retag-push-latest@main
        with:
          image: ${{ env.CI_REGISTRY_IMAGE }}
